"""
Milvus client for embedding operations and semantic search.

This module is responsible for all interaction with Milvus —
collection creation, vector upsert, and similarity search.

An important design decision here: we separate the Milvus client
from the embedding client (embedder). This allows swapping the embedding
model without affecting the persistence logic, and vice versa.

For local development, the MILVUS_URI variable can point to
a .db file (Milvus Lite) or to the standalone server in Docker.
"""

import json
from logging import getLogger
from datetime import datetime
from pymilvus import MilvusClient, DataType

logger = getLogger(__name__)

# Collection name in Milvus — equivalent to a table in SQL
COLLECTION_NAME = "procurements"

# Vector dimension generated by OpenAI's text-embedding-3-small.
# WARNING: if you switch the embedding model, this value must be updated
# and the collection must be recreated (vectors of different dimensions are incompatible).
EMBEDDING_DIM = 1536


class MilvusProcurementClient:
    """
    Abstracts all Milvus operations related to procurements.

    The idea is that Temporal Activities call high-level methods
    (upsert, search) without needing to know anything about schemas or indexes.
    All Milvus complexity is encapsulated here.
    """

    def __init__(self, uri: str):
        """
        uri can be:
          - "./procurements.db"        → Milvus Lite (local development)
          - "http://localhost:19530"   → Milvus standalone (Docker)
          - "https://..."              → Milvus Cloud (production)
        """
        self.client = MilvusClient(uri=uri)
        self._ensure_collection()

    def _ensure_collection(self):
        """
        Creates the collection if it does not exist.

        The 'ensure' strategy (create only if not exists) is preferable to
        'create or replace' because it preserves already-indexed data between
        worker restarts. In production, schema changes should be treated
        as explicit migrations.
        """
        if self.client.has_collection(COLLECTION_NAME):
            logger.info(f"Collection '{COLLECTION_NAME}' already exists — skipping creation.")
            return

        logger.info(f"Creating collection '{COLLECTION_NAME}'...")

        # We define the schema explicitly to control which fields
        # are available as filters in searches.
        schema = self.client.create_schema(auto_id=False, enable_dynamic_field=True)

        # Primary key — we use pncp_control_number as the natural ID
        # so that upsert is idempotent (reprocessing the same item
        # does not create duplicates).
        schema.add_field("id", DataType.VARCHAR, max_length=100, is_primary=True)

        # The vector itself — dimension defined by the chosen embedding model
        schema.add_field("vector", DataType.FLOAT_VECTOR, dim=EMBEDDING_DIM)

        # Metadata fields for hybrid filters (vector + structural filter).
        # Example: semantic search for "software development" filtered by state_acronym="SP"
        schema.add_field("state_acronym", DataType.VARCHAR, max_length=2, default_value="")
        schema.add_field("modality_id", DataType.INT64, default_value=0)
        schema.add_field("estimated_value", DataType.DOUBLE, default_value=0.0)
        schema.add_field("proposal_deadline", DataType.INT64, default_value=0)  # Unix timestamp
        schema.add_field("published_at", DataType.INT64, default_value=0)        # Unix timestamp

        # Vector index — AUTOINDEX lets Milvus choose the best algorithm
        # for the collection size. In production with millions of vectors,
        # it can be replaced with HNSW with explicit parameters.
        index_params = self.client.prepare_index_params()
        index_params.add_index(
            field_name="vector",
            index_type="AUTOINDEX",
            metric_type="COSINE",  # Cosine similarity is standard for text embeddings
        )

        self.client.create_collection(
            collection_name=COLLECTION_NAME,
            schema=schema,
            index_params=index_params,
        )
        logger.info(f"Collection '{COLLECTION_NAME}' created successfully.")

    def _build_record(self, item_json: str, embedding: list[float]) -> dict:
        item = json.loads(item_json)

        # Converts datetimes to Unix integer timestamps because
        # Milvus has no native datetime type — we use INT64
        # and compare with int(datetime.now().timestamp()) in queries.
        deadline_ts = 0
        if item.get("proposal_deadline"):
            try:
                dt = datetime.fromisoformat(item["proposal_deadline"])
                deadline_ts = int(dt.timestamp())
            except (ValueError, TypeError):
                pass

        published_ts = 0
        if item.get("published_at_pncp"):
            try:
                dt = datetime.fromisoformat(item["published_at_pncp"])
                published_ts = int(dt.timestamp())
            except (ValueError, TypeError):
                pass

        return {
            "id": item["pncp_control_number"],
            "vector": embedding,
            "state_acronym": item.get("contracting_unit", {}).get("state_acronym", "") or "",
            "modality_id": item.get("modality_id") or 0,
            "estimated_value": item.get("estimated_total_value") or 0.0,
            "proposal_deadline": deadline_ts,
            "published_at": published_ts,
        }

    def upsert(self, item_json: str, embedding: list[float]) -> None:
        """
        Inserts or updates a record in the collection.

        Upsert is idempotent by 'id' (pncp_control_number) —
        if the item already exists, vectors and metadata are updated.
        This ensures job reprocessing does not cause duplicates.
        """
        record = self._build_record(item_json, embedding)
        self.client.upsert(collection_name=COLLECTION_NAME, data=[record])

    def upsert_batch(self, items_json: list[str], embeddings: list[list[float]]) -> None:
        """
        Inserts or updates multiple records in the collection.
        """
        records = [
            self._build_record(item_json, embedding)
            for item_json, embedding in zip(items_json, embeddings)
        ]
        self.client.upsert(collection_name=COLLECTION_NAME, data=records)

    def search(
        self,
        query_vector: list[float],
        uf: str | None = None,
        modality_id: int | None = None,
        open_only: bool = False,
        limit: int = 10,
    ) -> list[dict]:
        """
        Semantic search with optional metadata filters.

        This is the operation that LangGraph Tools will call.
        Filters are boolean expressions in Milvus syntax —
        equivalent to SQL WHERE, but applied over vector metadata.

        Returns a list of dicts with 'id' (pncp_control_number) and
        'distance' (similarity score). The agent uses IDs to
        fetch complete data from Postgres via join.
        """
        filters = []

        if uf:
            filters.append(f'state_acronym == "{uf}"')

        if modality_id:
            filters.append(f"modality_id == {modality_id}")

        if open_only:
            now_ts = int(datetime.now().timestamp())
            filters.append(f"proposal_deadline > {now_ts}")

        filter_str = " && ".join(filters) if filters else ""

        results = self.client.search(
            collection_name=COLLECTION_NAME,
            data=[query_vector],
            filter=filter_str,
            limit=limit,
            output_fields=["id", "state_acronym", "modality_id", "proposal_deadline"],
        )

        # results is a list of lists (one per query vector)
        # since we always pass a single vector, we take results[0]
        return [
            {
                "id": hit["entity"]["id"],
                "score": hit["distance"],
                "state_acronym": hit["entity"].get("state_acronym"),
                "modality_id": hit["entity"].get("modality_id"),
            }
            for hit in results[0]
        ]

    def close(self):
        self.client.close()
