from enum import Enum


class Phases(str, Enum):
    INITIAL = "INITIAL"

    QUERY_REFINING = "QUERY_REFINING"

    CONTEXT_GATHERING = "CONTEXT_GATHERING"

    CONTEXT_CONSOLIDATION = "CONTEXT_CONSOLIDATION"

    PLANNING = "PLANNING"

    EXECUTING = "EXECUTING"

    WRAPPING_UP = "WRAPPING_UP"

    DONE = "DONE"

    ERROR = "ERROR"