"""initial schema

Revision ID: 0c75146a49e3
Revises: 
Create Date: 2026-05-30 18:00:28.498364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c75146a49e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procuring_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ibge_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=30), nullable=False),
    sa.Column('state_acronym', sa.String(length=2), nullable=False),
    sa.Column('unit_code', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=30), nullable=False),
    sa.Column('municipality_name', sa.String(length=30), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procuring_entity'))
    )
    op.create_index(op.f('ix_procuring_entity_cnpj'), 'procuring_entity', ['cnpj'], unique=True)
    op.create_table('procurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procuring_entity_id', sa.Integer(), nullable=False),
    sa.Column('pncp_control_number', sa.String(length=50), nullable=False),
    sa.Column('procurement_object', sa.Text(), nullable=False),
    sa.Column('additional_information', sa.Text(), nullable=False),
    sa.Column('estimated_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tender_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tender_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['procuring_entity_id'], ['procuring_entity.id'], name=op.f('fk_procurement_procuring_entity_id_procuring_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement'))
    )
    op.create_index(op.f('ix_procurement_pncp_control_number'), 'procurement', ['pncp_control_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_pncp_control_number'), table_name='procurement')
    op.drop_table('procurement')
    op.drop_index(op.f('ix_procuring_entity_cnpj'), table_name='procuring_entity')
    op.drop_table('procuring_entity')
    # ### end Alembic commands ###
